# Домашняя работа

## Задание 1
Напишите функцию, которая классифицирует фильмы из материалов занятия по правилам:

оценка 2 и ниже — низкий рейтинг;
оценка 4 и ниже — средний рейтинг;
оценка 4.5 и 5 — высокий рейтинг.
Результат классификации запишите в столбец class.

In [1]:
import pandas as pd

In [3]:
movies = pd.read_csv('movies.csv')
ratings = pd.read_csv('ratings.csv')

In [7]:
avg_df=ratings.groupby('movieId')['rating'].mean().reset_index()
final_df = pd.merge(
    movies, avg_df,
    left_on='movieId',
    right_on='movieId')

In [9]:
for i in range(len(final_df)):
    if round(final_df.loc[i, 'rating']) <= 2:
        final_df.loc[i, 'class'] = 'низкий рейтинг'
    elif round(final_df.loc[i, 'rating']) <= 4:
        final_df.loc[i, 'class'] = 'средний рейтинг'
    elif round(final_df.loc[i, 'rating']) >= 4.5:
        final_df.loc[i, 'class'] = 'высокий рейтинг'  
        
final_df.sort_values('rating',ascending=False)

,movieId,title,genres,rating,class
7638,88448,Paper Birds (Pájaros de papel) (2010),Comedy|Drama,5.0,высокий рейтинг
8089,100556,"Act of Killing, The (2012)",Documentary,5.0,высокий рейтинг
9065,143031,Jump In! (2007),Comedy|Drama|Romance,5.0,высокий рейтинг
9076,143511,Human (2015),Documentary,5.0,высокий рейтинг
9078,143559,L.A. Slasher (2015),Comedy|Crime|Fantasy,5.0,высокий рейтинг
...,...,...,...,...,...
9253,157172,Wizards of the Lost Kingdom II (1989),Action|Fantasy,0.5,низкий рейтинг
7536,85334,Hard Ticket to Hawaii (1987),Action|Comedy,0.5,низкий рейтинг
6486,53453,Starcrash (a.k.a. Star Crash) (1978),Action|Adventure|Fantasy|Sci-Fi,0.5,низкий рейтинг
5200,8494,"Cincinnati Kid, The (1965)",Drama,0.5,низкий рейтинг
7145,71810,Legionnaire (1998),Action|Adventure|Drama|War,0.5,низкий рейтинг

## Задание 2
Используйте файл keywords.csv.

Нужно написать гео-классификатор, который каждой строке сможет выставить географическую при надлежность определённому региону. Т. е. если поисковый запрос содержит название города региона, то в столбце ‘region’ пишется название этого региона. Если поисковый запрос не содержит названия города, то ставим ‘undefined’.

Правила распределения по регионам Центр, Северо-Запад и Дальний Восток: 

**geo_data** = {
    'Центр': ['москва', 'тула', 'ярославль'],
    'Северо-Запад': ['петербург', 'псков', 'мурманск'],
    'Дальний Восток': ['владивосток', 'сахалин', 'хабаровск']
}

In [11]:
import re

In [13]:
keywords = pd.read_csv('keywords.csv')
geo_data = {
    'Центр': ['москва', 'тула', 'ярославль'],
    'Северо-Запад': ['петербург', 'псков', 'мурманск'],
    'Дальний Восток': ['владивосток', 'сахалин', 'хабаровск']
}

In [15]:
def classify_region(keyword):
    for region, cities in geo_data.items():
        for city in cities:
            if re.search(r'\b' + re.escape(city) + r'\b', keyword, re.IGNORECASE):
                return region
    return 'undefined'

In [17]:
keywords['region'] = keywords['keyword'].apply(classify_region)
keywords.sort_values('region',ascending=True)

                                                 keyword     shows     region
0                                                     вк  64292779  undefined
66565                         терранова официальный сайт      5326  undefined
66564                                      штамм 1 сезон      5390  undefined
66563                                         япона мама      5288  undefined
66562                                           аперитив      5287  undefined
...                                                  ...       ...        ...
78820  садовод рынок москва цены на товары каталог 20...      4511      Центр
7339                              москва слезам не верит     35857      Центр
94336                           киносити тула расписание      4062      Центр
67686                         цска хоккейный клуб москва      5548      Центр
49999                                       avito москва      6876      Центр

[100000 rows x 3 columns]

In [19]:
avg_df2=keywords.groupby('region').size().reset_index(name='count').sort_values('count',ascending=True)
avg_df2

           region  count
1  Дальний Восток     64
2    Северо-Запад    146
3           Центр    384
0       undefined  99406